//
//  ___FILENAME___
//  ___PROJECTNAME___
//
//  Created by ___FULLUSERNAME___ on ___DATE___.
//  Copyright © ___YEAR___ ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift HELM Xcode Templates
//

import UIKit

// Implemented by ___FILEBASENAMEASIDENTIFIER___Interactor
protocol ___FILEBASENAMEASIDENTIFIER___InteractorInput {

}

// Implemented by ___FILEBASENAMEASIDENTIFIER___Presenter
protocol ___FILEBASENAMEASIDENTIFIER___InteractorOutput {

}

// Implemented by ___FILEBASENAMEASIDENTIFIER___Interactor
protocol ___FILEBASENAMEASIDENTIFIER___DataSource {

}

// Implemented by ___FILEBASENAMEASIDENTIFIER___Interactor
protocol ___FILEBASENAMEASIDENTIFIER___DataDestination {

}

class ___FILEBASENAMEASIDENTIFIER___Interactor: ___FILEBASENAMEASIDENTIFIER___InteractorInput, ___FILEBASENAMEASIDENTIFIER___DataSource, ___FILEBASENAMEASIDENTIFIER___DataDestination {

  var output: ___FILEBASENAMEASIDENTIFIER___InteractorOutput!

  // MARK: Business logic

}
